name: Build site
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: parafoxia/pip-install@v1
        with:
          packages: autosite

      - name: Build
        run: autosite -a

      - name: Deploy
        uses: bcomnes/deploy-to-neocities@v1
        with:
          api_token: ${{ secrets.APIKEY }}
          dist_dir: out
          cleanup: false
