name: Build site
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate RSS
        uses: tabhub/rssify@master
        with:
          title: LensDeer's Hideout - Microblog RSS
          url: https://lensdeer.neocities.org/microblog.html
          item-title-css: h1
          item-description-css: .tag
          item-date-css: time
          item-date-format: YYYY - MM - DD

      - name: Run Makefile
        run: make

      - name: Deploy
        uses: bcomnes/deploy-to-neocities@v1
        with:
          api_token: ${{ secrets.APIKEY }}
          dist_dir: _build
          cleanup: false
