name: Build site
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Dependencies
        uses: BSFishy/pip-action@v1
        with:
          packages: autosite

      - name: Autosite
        run: autosite -a

      - name: Deploy
        uses: bcomnes/deploy-to-neocities@v1
        with:
          api_token: ${{ secrets.APIKEY }}
          dist_dir: out
          cleanup: false
