name: Build site
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
        run: pip install autosite

      - name: Autosite
         run: autosite -a

      - name: Deploy
        uses: bcomnes/deploy-to-neocities@v1
        with:
          api_token: ${{ secrets.APIKEY }}
          dist_dir: out
          cleanup: false
